names = ["me", "you", "he", "her"]
print(names[0])
print(names[1])
print(names[2])
print(names[-1])
print("---------------")
print(f"Hello{names[0].title()}, nice to meet you")
print(f"Hello{names[1].title()}, nice to meet you")
print(f"Hello{names[2].title()}, nice to meet you")
print(f"Hello{names[3].title()}, nice to meet you")
print("--------------")
wishlist = ("iphone", "ipad")
print(f"私は{wishlist[0].title()}がほしい。")
